import { type User, type InsertUser, type AgentType, type PromptStatus, type RunOutcome as SchemaRunOutcome, type InsertRunOutcome as SchemaInsertRunOutcome, type HumanFeedback as SchemaHumanFeedback, type InsertHumanFeedback as SchemaInsertHumanFeedback, type PromptVariant as SchemaPromptVariant, type InsertPromptVariant as SchemaInsertPromptVariant, type MemoryEntry as SchemaMemoryEntry, type InsertMemoryEntry as SchemaInsertMemoryEntry, type AgentReport as SchemaAgentReport, type InsertAgentReport as SchemaInsertAgentReport, type ProjectGuidelines as SchemaProjectGuidelines, type InsertProjectGuidelines as SchemaInsertProjectGuidelines, type FailurePattern as SchemaFailurePattern, type InsertFailurePattern as SchemaInsertFailurePattern, type FailureCategory, type MonitorAnalytics, insertRunOutcomeSchema, insertHumanFeedbackSchema, insertPromptVariantSchema, insertMemoryEntrySchema, insertAgentReportSchema, insertProjectGuidelinesSchema, insertFailurePatternSchema } from "@shared/schema";
export type RunOutcome = SchemaRunOutcome;
export type InsertRunOutcome = SchemaInsertRunOutcome;
export type HumanFeedback = SchemaHumanFeedback;
export type InsertHumanFeedback = SchemaInsertHumanFeedback;
export type PromptVariant = SchemaPromptVariant;
export type InsertPromptVariant = SchemaInsertPromptVariant;
export type MemoryEntry = SchemaMemoryEntry;
export type InsertMemoryEntry = SchemaInsertMemoryEntry;
export type AgentReport = SchemaAgentReport;
export type InsertAgentReport = SchemaInsertAgentReport;
export type ProjectGuidelines = SchemaProjectGuidelines;
export type InsertProjectGuidelines = SchemaInsertProjectGuidelines;
export type FailurePattern = SchemaFailurePattern;
export type InsertFailurePattern = SchemaInsertFailurePattern;
export { insertRunOutcomeSchema, insertHumanFeedbackSchema, insertPromptVariantSchema, insertMemoryEntrySchema, insertAgentReportSchema, insertProjectGuidelinesSchema, insertFailurePatternSchema, };
export interface IStorage {
    getUser(id: string): Promise<User | undefined>;
    getUserByUsername(username: string): Promise<User | undefined>;
    createUser(user: InsertUser): Promise<User>;
}
export interface IDataTelemetry {
    createRunOutcome(outcome: InsertRunOutcome): Promise<RunOutcome>;
    getRunOutcome(runId: string): Promise<RunOutcome | undefined>;
    getRunOutcomesByAgent(agentType: AgentType, limit?: number): Promise<RunOutcome[]>;
    updateRunOutcome(runId: string, updates: Partial<InsertRunOutcome>): Promise<RunOutcome | undefined>;
    getAcceptanceRate(agentType: AgentType): Promise<number>;
    cleanupOldOutcomes(retentionDays: number): Promise<number>;
    createFeedback(feedback: InsertHumanFeedback): Promise<HumanFeedback>;
    getFeedbackByRunId(runId: string): Promise<HumanFeedback | undefined>;
    getFeedbackByTags(tags: string[], limit?: number): Promise<HumanFeedback[]>;
    createPromptVariant(variant: InsertPromptVariant): Promise<PromptVariant>;
    getPromptVariant(id: string): Promise<PromptVariant | undefined>;
    getPromotedVariant(agentType: AgentType): Promise<PromptVariant | undefined>;
    getVariantsByStatus(agentType: AgentType, status: PromptStatus): Promise<PromptVariant[]>;
    updatePromptVariant(id: string, updates: Partial<InsertPromptVariant>): Promise<PromptVariant | undefined>;
    getNextVersionNumber(agentType: AgentType): Promise<number>;
    createMemoryEntry(entry: InsertMemoryEntry): Promise<MemoryEntry>;
    getMemoryEntry(id: string): Promise<MemoryEntry | undefined>;
    findSimilarMemories(agentType: AgentType, embedding: number[], limit?: number): Promise<MemoryEntry[]>;
    incrementAccessCount(id: string): Promise<void>;
    cleanupExpiredMemories(): Promise<number>;
}
export interface IAgentMonitor {
    createAgentReport(report: InsertAgentReport): Promise<AgentReport>;
    getAgentReport(id: string): Promise<AgentReport | undefined>;
    getAgentReportsByProject(projectId: string, limit?: number): Promise<AgentReport[]>;
    getAgentReportsByCategory(category: FailureCategory, limit?: number): Promise<AgentReport[]>;
    getAgentReportsWithFailures(projectId: string): Promise<AgentReport[]>;
    cleanupOldReports(retentionDays: number): Promise<number>;
    createProjectGuidelines(guidelines: InsertProjectGuidelines): Promise<ProjectGuidelines>;
    getProjectGuidelines(projectId: string): Promise<ProjectGuidelines | undefined>;
    updateProjectGuidelines(projectId: string, updates: Partial<InsertProjectGuidelines>): Promise<ProjectGuidelines | undefined>;
    createFailurePattern(pattern: InsertFailurePattern): Promise<FailurePattern>;
    getFailurePattern(id: string): Promise<FailurePattern | undefined>;
    getFailurePatternsByProject(projectId: string): Promise<FailurePattern[]>;
    getFailurePatternsByCategory(category: FailureCategory): Promise<FailurePattern[]>;
    getGlobalPatterns(): Promise<FailurePattern[]>;
    incrementPatternOccurrence(id: string): Promise<FailurePattern | undefined>;
    updateFailurePattern(id: string, updates: Partial<InsertFailurePattern>): Promise<FailurePattern | undefined>;
    getMonitorAnalytics(projectId?: string): Promise<MonitorAnalytics>;
}
export declare class MemStorage implements IStorage, IDataTelemetry, IAgentMonitor {
    private users;
    private runOutcomes;
    private humanFeedbackStore;
    private promptVariants;
    private memoryEntries;
    private agentReports;
    private projectGuidelinesStore;
    private failurePatternsStore;
    constructor();
    getUser(id: string): Promise<User | undefined>;
    getUserByUsername(username: string): Promise<User | undefined>;
    createUser(insertUser: InsertUser): Promise<User>;
    createRunOutcome(outcome: InsertRunOutcome): Promise<RunOutcome>;
    getRunOutcome(runId: string): Promise<RunOutcome | undefined>;
    getRunOutcomesByAgent(agentType: AgentType, limit?: number): Promise<RunOutcome[]>;
    updateRunOutcome(runId: string, updates: Partial<InsertRunOutcome>): Promise<RunOutcome | undefined>;
    getAcceptanceRate(agentType: AgentType): Promise<number>;
    cleanupOldOutcomes(retentionDays: number): Promise<number>;
    createFeedback(feedback: InsertHumanFeedback): Promise<HumanFeedback>;
    getFeedbackByRunId(runId: string): Promise<HumanFeedback | undefined>;
    getFeedbackByTags(tags: string[], limit?: number): Promise<HumanFeedback[]>;
    createPromptVariant(variant: InsertPromptVariant): Promise<PromptVariant>;
    getPromptVariant(id: string): Promise<PromptVariant | undefined>;
    getPromotedVariant(agentType: AgentType): Promise<PromptVariant | undefined>;
    getVariantsByStatus(agentType: AgentType, status: PromptStatus): Promise<PromptVariant[]>;
    updatePromptVariant(id: string, updates: Partial<InsertPromptVariant>): Promise<PromptVariant | undefined>;
    getNextVersionNumber(agentType: AgentType): Promise<number>;
    createMemoryEntry(entry: InsertMemoryEntry): Promise<MemoryEntry>;
    getMemoryEntry(id: string): Promise<MemoryEntry | undefined>;
    findSimilarMemories(agentType: AgentType, embedding: number[], limit?: number): Promise<MemoryEntry[]>;
    incrementAccessCount(id: string): Promise<void>;
    cleanupExpiredMemories(): Promise<number>;
    createAgentReport(report: InsertAgentReport): Promise<AgentReport>;
    getAgentReport(id: string): Promise<AgentReport | undefined>;
    getAgentReportsByProject(projectId: string, limit?: number): Promise<AgentReport[]>;
    getAgentReportsByCategory(category: FailureCategory, limit?: number): Promise<AgentReport[]>;
    getAgentReportsWithFailures(projectId: string): Promise<AgentReport[]>;
    cleanupOldReports(retentionDays: number): Promise<number>;
    createProjectGuidelines(guidelines: InsertProjectGuidelines): Promise<ProjectGuidelines>;
    getProjectGuidelines(projectId: string): Promise<ProjectGuidelines | undefined>;
    updateProjectGuidelines(projectId: string, updates: Partial<InsertProjectGuidelines>): Promise<ProjectGuidelines | undefined>;
    createFailurePattern(pattern: InsertFailurePattern): Promise<FailurePattern>;
    getFailurePattern(id: string): Promise<FailurePattern | undefined>;
    getFailurePatternsByProject(projectId: string): Promise<FailurePattern[]>;
    getFailurePatternsByCategory(category: FailureCategory): Promise<FailurePattern[]>;
    getGlobalPatterns(): Promise<FailurePattern[]>;
    incrementPatternOccurrence(id: string): Promise<FailurePattern | undefined>;
    updateFailurePattern(id: string, updates: Partial<InsertFailurePattern>): Promise<FailurePattern | undefined>;
    getMonitorAnalytics(projectId?: string): Promise<MonitorAnalytics>;
}
export declare const storage: MemStorage;
//# sourceMappingURL=storage.d.ts.map