import { z } from "zod";
export declare const users: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "users";
    schema: undefined;
    columns: {
        id: import("drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "users";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {
            length: number | undefined;
        }>;
        username: import("drizzle-orm/pg-core").PgColumn<{
            name: "username";
            tableName: "users";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        password: import("drizzle-orm/pg-core").PgColumn<{
            name: "password";
            tableName: "users";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const insertUserSchema: z.ZodObject<Pick<{
    id: z.ZodOptional<z.ZodString>;
    username: z.ZodString;
    password: z.ZodString;
}, "username" | "password">, "strip", z.ZodTypeAny, {
    username: string;
    password: string;
}, {
    username: string;
    password: string;
}>;
export type InsertUser = z.infer<typeof insertUserSchema>;
export type User = typeof users.$inferSelect;
export type AgentType = "architect" | "mechanic" | "codeNinja" | "philosopher";
export type ConsistencyMode = "none" | "fast" | "robust";
export type ValidationLevel = "low" | "medium" | "high" | "strict";
export declare const agentInvocations: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "agent_invocations";
    schema: undefined;
    columns: {
        id: import("drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "agent_invocations";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {
            length: number | undefined;
        }>;
        agentType: import("drizzle-orm/pg-core").PgColumn<{
            name: "agent_type";
            tableName: "agent_invocations";
            dataType: "string";
            columnType: "PgText";
            data: AgentType;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {
            $type: AgentType;
        }>;
        prompt: import("drizzle-orm/pg-core").PgColumn<{
            name: "prompt";
            tableName: "agent_invocations";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        response: import("drizzle-orm/pg-core").PgColumn<{
            name: "response";
            tableName: "agent_invocations";
            dataType: "json";
            columnType: "PgJsonb";
            data: unknown;
            driverParam: unknown;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        reasoning: import("drizzle-orm/pg-core").PgColumn<{
            name: "reasoning";
            tableName: "agent_invocations";
            dataType: "json";
            columnType: "PgJsonb";
            data: string[];
            driverParam: unknown;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {
            $type: string[];
        }>;
        confidence: import("drizzle-orm/pg-core").PgColumn<{
            name: "confidence";
            tableName: "agent_invocations";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        metrics: import("drizzle-orm/pg-core").PgColumn<{
            name: "metrics";
            tableName: "agent_invocations";
            dataType: "json";
            columnType: "PgJsonb";
            data: unknown;
            driverParam: unknown;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        createdAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "created_at";
            tableName: "agent_invocations";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const insertAgentInvocationSchema: z.ZodObject<Omit<{
    id: z.ZodOptional<z.ZodString>;
    agentType: z.ZodString;
    prompt: z.ZodString;
    response: z.ZodOptional<z.ZodNullable<z.ZodType<import("drizzle-zod").Json, z.ZodTypeDef, import("drizzle-zod").Json>>>;
    reasoning: z.ZodOptional<z.ZodNullable<z.ZodType<string[], z.ZodTypeDef, string[]>>>;
    confidence: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    metrics: z.ZodOptional<z.ZodNullable<z.ZodType<import("drizzle-zod").Json, z.ZodTypeDef, import("drizzle-zod").Json>>>;
    createdAt: z.ZodOptional<z.ZodDate>;
}, "id" | "createdAt">, "strip", z.ZodTypeAny, {
    agentType: string;
    prompt: string;
    response?: import("drizzle-zod").Json | undefined;
    reasoning?: string[] | null | undefined;
    metrics?: import("drizzle-zod").Json | undefined;
    confidence?: number | null | undefined;
}, {
    agentType: string;
    prompt: string;
    response?: import("drizzle-zod").Json | undefined;
    reasoning?: string[] | null | undefined;
    metrics?: import("drizzle-zod").Json | undefined;
    confidence?: number | null | undefined;
}>;
export type InsertAgentInvocation = z.infer<typeof insertAgentInvocationSchema>;
export type AgentInvocation = typeof agentInvocations.$inferSelect;
export interface ReasoningStep {
    step: number;
    thought: string;
    action?: string;
    observation?: string;
}
export interface AgentResponse {
    reasoning: ReasoningStep[];
    recommendation: string;
    confidence: number;
    alternatives?: string[];
    warnings?: string[];
    codeOutput?: string;
    validations: {
        passed: string[];
        failed: string[];
    };
    grokSecondOpinion?: GrokSecondOpinion;
}
export interface CLASSicMetrics {
    cost: {
        tokens: number;
        inputTokens: number;
        outputTokens: number;
        estimatedCost: number;
    };
    latency: {
        totalMs: number;
        perStepMs: number[];
    };
    accuracy: {
        taskSuccessRate: number;
        validationsPassed: number;
        validationsFailed: number;
    };
    security: {
        promptInjectionBlocked: boolean;
        safeCodeGenerated: boolean;
    };
    stability: {
        consistencyScore: number;
        hallucinationDetected: boolean;
        pathsEvaluated: number;
    };
}
export interface AgentConfig {
    consistencyMode: ConsistencyMode;
    validationLevel: ValidationLevel;
    enableSelfCritique: boolean;
    enablePhilosopher: boolean;
    enableGrokSecondOpinion: boolean;
    maxTokens: number;
    temperature: number;
}
export interface GrokSecondOpinion {
    content: string;
    model: string;
    rating?: number;
    agreements: string[];
    improvements: string[];
    risks: string[];
}
export interface ReplitMdConfig {
    agentConfig: Partial<AgentConfig>;
    codeStandards: string[];
    architecturalRules: string[];
    securityConstraints: string[];
    customInstructions: string[];
}
export declare const DEFAULT_AGENT_CONFIG: AgentConfig;
export interface AgentPersona {
    id: AgentType;
    name: string;
    tagline: string;
    description: string;
    capabilities: string[];
    icon: string;
    color: string;
}
export declare const AGENT_PERSONAS: AgentPersona[];
export declare const OUTCOME_STATUSES: readonly ["accepted", "rejected", "edited", "ignored"];
export type OutcomeStatus = typeof OUTCOME_STATUSES[number];
export declare const PROMPT_STATUSES: readonly ["shadow", "ab_test", "promoted", "retired"];
export type PromptStatus = typeof PROMPT_STATUSES[number];
export declare const FEEDBACK_TAGS: readonly ["too_verbose", "too_brief", "incorrect", "off_topic", "helpful", "creative", "slow", "confusing"];
export type FeedbackTag = typeof FEEDBACK_TAGS[number];
export interface PromptMetrics {
    acceptanceRate: number;
    avgEditDistance: number;
    avgLatency: number;
    sampleSize: number;
    pValue?: number;
}
export interface StoredCLASSicMetrics {
    cost: number;
    latency: number;
    accuracy: number;
    security: number;
    stability: number;
}
export declare const runOutcomes: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "run_outcomes";
    schema: undefined;
    columns: {
        id: import("drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "run_outcomes";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {
            length: number | undefined;
        }>;
        runId: import("drizzle-orm/pg-core").PgColumn<{
            name: "run_id";
            tableName: "run_outcomes";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        agentType: import("drizzle-orm/pg-core").PgColumn<{
            name: "agent_type";
            tableName: "run_outcomes";
            dataType: "string";
            columnType: "PgText";
            data: AgentType;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {
            $type: AgentType;
        }>;
        outcomeStatus: import("drizzle-orm/pg-core").PgColumn<{
            name: "outcome_status";
            tableName: "run_outcomes";
            dataType: "string";
            columnType: "PgText";
            data: "accepted" | "rejected" | "edited" | "ignored";
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {
            $type: "accepted" | "rejected" | "edited" | "ignored";
        }>;
        editDistance: import("drizzle-orm/pg-core").PgColumn<{
            name: "edit_distance";
            tableName: "run_outcomes";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        timeToDecision: import("drizzle-orm/pg-core").PgColumn<{
            name: "time_to_decision_ms";
            tableName: "run_outcomes";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        grokAgreed: import("drizzle-orm/pg-core").PgColumn<{
            name: "grok_agreed";
            tableName: "run_outcomes";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        classicMetrics: import("drizzle-orm/pg-core").PgColumn<{
            name: "classic_metrics";
            tableName: "run_outcomes";
            dataType: "json";
            columnType: "PgJsonb";
            data: StoredCLASSicMetrics;
            driverParam: unknown;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {
            $type: StoredCLASSicMetrics;
        }>;
        promptVersion: import("drizzle-orm/pg-core").PgColumn<{
            name: "prompt_version";
            tableName: "run_outcomes";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        createdAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "created_at";
            tableName: "run_outcomes";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const insertRunOutcomeSchema: z.ZodObject<Omit<{
    id: z.ZodOptional<z.ZodString>;
    runId: z.ZodString;
    agentType: z.ZodString;
    outcomeStatus: z.ZodString;
    editDistance: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    timeToDecision: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    grokAgreed: z.ZodOptional<z.ZodNullable<z.ZodBoolean>>;
    classicMetrics: z.ZodOptional<z.ZodNullable<z.ZodType<StoredCLASSicMetrics, z.ZodTypeDef, StoredCLASSicMetrics>>>;
    promptVersion: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    createdAt: z.ZodOptional<z.ZodDate>;
}, "id" | "createdAt">, "strip", z.ZodTypeAny, {
    agentType: string;
    runId: string;
    outcomeStatus: string;
    editDistance?: number | null | undefined;
    timeToDecision?: number | null | undefined;
    grokAgreed?: boolean | null | undefined;
    classicMetrics?: StoredCLASSicMetrics | null | undefined;
    promptVersion?: string | null | undefined;
}, {
    agentType: string;
    runId: string;
    outcomeStatus: string;
    editDistance?: number | null | undefined;
    timeToDecision?: number | null | undefined;
    grokAgreed?: boolean | null | undefined;
    classicMetrics?: StoredCLASSicMetrics | null | undefined;
    promptVersion?: string | null | undefined;
}>;
export type InsertRunOutcome = z.infer<typeof insertRunOutcomeSchema>;
export type RunOutcome = typeof runOutcomes.$inferSelect;
export declare const humanFeedback: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "human_feedback";
    schema: undefined;
    columns: {
        id: import("drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "human_feedback";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {
            length: number | undefined;
        }>;
        runId: import("drizzle-orm/pg-core").PgColumn<{
            name: "run_id";
            tableName: "human_feedback";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        rating: import("drizzle-orm/pg-core").PgColumn<{
            name: "rating";
            tableName: "human_feedback";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        tags: import("drizzle-orm/pg-core").PgColumn<{
            name: "tags";
            tableName: "human_feedback";
            dataType: "array";
            columnType: "PgArray";
            data: string[];
            driverParam: string | string[];
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: import("drizzle-orm").Column<{
                name: "tags";
                tableName: "human_feedback";
                dataType: "string";
                columnType: "PgText";
                data: string;
                driverParam: string;
                notNull: false;
                hasDefault: false;
                isPrimaryKey: false;
                isAutoincrement: false;
                hasRuntimeDefault: false;
                enumValues: [string, ...string[]];
                baseColumn: never;
                identity: undefined;
                generated: undefined;
            }, {}, {}>;
            identity: undefined;
            generated: undefined;
        }, {}, {
            baseBuilder: import("drizzle-orm/pg-core").PgColumnBuilder<{
                name: "tags";
                dataType: "string";
                columnType: "PgText";
                data: string;
                enumValues: [string, ...string[]];
                driverParam: string;
            }, {}, {}, import("drizzle-orm").ColumnBuilderExtraConfig>;
            size: undefined;
        }>;
        comment: import("drizzle-orm/pg-core").PgColumn<{
            name: "comment";
            tableName: "human_feedback";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        submittedAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "submitted_at";
            tableName: "human_feedback";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const insertHumanFeedbackSchema: z.ZodObject<Omit<{
    id: z.ZodOptional<z.ZodString>;
    runId: z.ZodString;
    rating: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    tags: z.ZodOptional<z.ZodNullable<z.ZodArray<z.ZodString, "many">>>;
    comment: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    submittedAt: z.ZodOptional<z.ZodDate>;
}, "id" | "submittedAt">, "strip", z.ZodTypeAny, {
    runId: string;
    rating?: number | null | undefined;
    tags?: string[] | null | undefined;
    comment?: string | null | undefined;
}, {
    runId: string;
    rating?: number | null | undefined;
    tags?: string[] | null | undefined;
    comment?: string | null | undefined;
}>;
export type InsertHumanFeedback = z.infer<typeof insertHumanFeedbackSchema>;
export type HumanFeedback = typeof humanFeedback.$inferSelect;
export declare const promptVariants: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "prompt_variants";
    schema: undefined;
    columns: {
        id: import("drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "prompt_variants";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {
            length: number | undefined;
        }>;
        agentType: import("drizzle-orm/pg-core").PgColumn<{
            name: "agent_type";
            tableName: "prompt_variants";
            dataType: "string";
            columnType: "PgText";
            data: AgentType;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {
            $type: AgentType;
        }>;
        version: import("drizzle-orm/pg-core").PgColumn<{
            name: "version";
            tableName: "prompt_variants";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        promptText: import("drizzle-orm/pg-core").PgColumn<{
            name: "prompt_text";
            tableName: "prompt_variants";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        status: import("drizzle-orm/pg-core").PgColumn<{
            name: "status";
            tableName: "prompt_variants";
            dataType: "string";
            columnType: "PgText";
            data: "shadow" | "ab_test" | "promoted" | "retired";
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {
            $type: "shadow" | "ab_test" | "promoted" | "retired";
        }>;
        trafficPercent: import("drizzle-orm/pg-core").PgColumn<{
            name: "traffic_percent";
            tableName: "prompt_variants";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        metrics: import("drizzle-orm/pg-core").PgColumn<{
            name: "metrics";
            tableName: "prompt_variants";
            dataType: "json";
            columnType: "PgJsonb";
            data: PromptMetrics;
            driverParam: unknown;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {
            $type: PromptMetrics;
        }>;
        createdAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "created_at";
            tableName: "prompt_variants";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        promotedAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "promoted_at";
            tableName: "prompt_variants";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        retiredAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "retired_at";
            tableName: "prompt_variants";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const insertPromptVariantSchema: z.ZodObject<Omit<{
    id: z.ZodOptional<z.ZodString>;
    agentType: z.ZodString;
    version: z.ZodNumber;
    promptText: z.ZodString;
    status: z.ZodString;
    trafficPercent: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    metrics: z.ZodOptional<z.ZodNullable<z.ZodType<PromptMetrics, z.ZodTypeDef, PromptMetrics>>>;
    createdAt: z.ZodOptional<z.ZodDate>;
    promotedAt: z.ZodOptional<z.ZodNullable<z.ZodDate>>;
    retiredAt: z.ZodOptional<z.ZodNullable<z.ZodDate>>;
}, "id" | "createdAt">, "strip", z.ZodTypeAny, {
    version: number;
    agentType: string;
    status: string;
    promptText: string;
    metrics?: PromptMetrics | null | undefined;
    trafficPercent?: number | null | undefined;
    promotedAt?: Date | null | undefined;
    retiredAt?: Date | null | undefined;
}, {
    version: number;
    agentType: string;
    status: string;
    promptText: string;
    metrics?: PromptMetrics | null | undefined;
    trafficPercent?: number | null | undefined;
    promotedAt?: Date | null | undefined;
    retiredAt?: Date | null | undefined;
}>;
export type InsertPromptVariant = z.infer<typeof insertPromptVariantSchema>;
export type PromptVariant = typeof promptVariants.$inferSelect;
export declare const memoryEntries: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "memory_entries";
    schema: undefined;
    columns: {
        id: import("drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "memory_entries";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {
            length: number | undefined;
        }>;
        agentType: import("drizzle-orm/pg-core").PgColumn<{
            name: "agent_type";
            tableName: "memory_entries";
            dataType: "string";
            columnType: "PgText";
            data: AgentType;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {
            $type: AgentType;
        }>;
        taskDescription: import("drizzle-orm/pg-core").PgColumn<{
            name: "task_description";
            tableName: "memory_entries";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        taskEmbedding: import("drizzle-orm/pg-core").PgColumn<{
            name: "task_embedding";
            tableName: "memory_entries";
            dataType: "array";
            columnType: "PgArray";
            data: number[];
            driverParam: string | (string | number)[];
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: import("drizzle-orm").Column<{
                name: "task_embedding";
                tableName: "memory_entries";
                dataType: "number";
                columnType: "PgReal";
                data: number;
                driverParam: string | number;
                notNull: false;
                hasDefault: false;
                isPrimaryKey: false;
                isAutoincrement: false;
                hasRuntimeDefault: false;
                enumValues: undefined;
                baseColumn: never;
                identity: undefined;
                generated: undefined;
            }, {}, {}>;
            identity: undefined;
            generated: undefined;
        }, {}, {
            baseBuilder: import("drizzle-orm/pg-core").PgColumnBuilder<{
                name: "task_embedding";
                dataType: "number";
                columnType: "PgReal";
                data: number;
                driverParam: string | number;
                enumValues: undefined;
            }, {}, {}, import("drizzle-orm").ColumnBuilderExtraConfig>;
            size: undefined;
        }>;
        response: import("drizzle-orm/pg-core").PgColumn<{
            name: "response";
            tableName: "memory_entries";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        qualityScore: import("drizzle-orm/pg-core").PgColumn<{
            name: "quality_score";
            tableName: "memory_entries";
            dataType: "number";
            columnType: "PgReal";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        accessCount: import("drizzle-orm/pg-core").PgColumn<{
            name: "access_count";
            tableName: "memory_entries";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        createdAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "created_at";
            tableName: "memory_entries";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        expiresAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "expires_at";
            tableName: "memory_entries";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const insertMemoryEntrySchema: z.ZodObject<Omit<{
    id: z.ZodOptional<z.ZodString>;
    agentType: z.ZodString;
    taskDescription: z.ZodString;
    taskEmbedding: z.ZodOptional<z.ZodNullable<z.ZodArray<z.ZodNumber, "many">>>;
    response: z.ZodString;
    qualityScore: z.ZodNumber;
    accessCount: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    createdAt: z.ZodOptional<z.ZodDate>;
    expiresAt: z.ZodDate;
}, "id" | "createdAt" | "accessCount">, "strip", z.ZodTypeAny, {
    response: string;
    agentType: string;
    taskDescription: string;
    qualityScore: number;
    expiresAt: Date;
    taskEmbedding?: number[] | null | undefined;
}, {
    response: string;
    agentType: string;
    taskDescription: string;
    qualityScore: number;
    expiresAt: Date;
    taskEmbedding?: number[] | null | undefined;
}>;
export type InsertMemoryEntry = z.infer<typeof insertMemoryEntrySchema>;
export type MemoryEntry = typeof memoryEntries.$inferSelect;
export declare const EXTERNAL_AGENT_TYPES: readonly ["replit_agent", "cursor", "copilot", "claude_code", "windsurf", "aider", "continue", "cody", "unknown"];
export type ExternalAgentType = typeof EXTERNAL_AGENT_TYPES[number];
export declare const FAILURE_CATEGORIES: readonly ["security_gap", "logic_error", "context_blindness", "outdated_api", "missing_edge_case", "poor_readability", "broke_existing", "hallucinated_code"];
export type FailureCategory = typeof FAILURE_CATEGORIES[number];
export declare const FAILURE_SEVERITIES: readonly ["low", "medium", "high", "critical"];
export type FailureSeverity = typeof FAILURE_SEVERITIES[number];
export declare const agentReports: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "agent_reports";
    schema: undefined;
    columns: {
        id: import("drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "agent_reports";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {
            length: number | undefined;
        }>;
        projectId: import("drizzle-orm/pg-core").PgColumn<{
            name: "project_id";
            tableName: "agent_reports";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        externalAgent: import("drizzle-orm/pg-core").PgColumn<{
            name: "external_agent";
            tableName: "agent_reports";
            dataType: "string";
            columnType: "PgText";
            data: "replit_agent" | "cursor" | "copilot" | "claude_code" | "windsurf" | "aider" | "continue" | "cody" | "unknown";
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {
            $type: "replit_agent" | "cursor" | "copilot" | "claude_code" | "windsurf" | "aider" | "continue" | "cody" | "unknown";
        }>;
        sessionId: import("drizzle-orm/pg-core").PgColumn<{
            name: "session_id";
            tableName: "agent_reports";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        action: import("drizzle-orm/pg-core").PgColumn<{
            name: "action";
            tableName: "agent_reports";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        codeGenerated: import("drizzle-orm/pg-core").PgColumn<{
            name: "code_generated";
            tableName: "agent_reports";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        codeAccepted: import("drizzle-orm/pg-core").PgColumn<{
            name: "code_accepted";
            tableName: "agent_reports";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        humanCorrection: import("drizzle-orm/pg-core").PgColumn<{
            name: "human_correction";
            tableName: "agent_reports";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        errorMessage: import("drizzle-orm/pg-core").PgColumn<{
            name: "error_message";
            tableName: "agent_reports";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        failureCategory: import("drizzle-orm/pg-core").PgColumn<{
            name: "failure_category";
            tableName: "agent_reports";
            dataType: "string";
            columnType: "PgText";
            data: "security_gap" | "logic_error" | "context_blindness" | "outdated_api" | "missing_edge_case" | "poor_readability" | "broke_existing" | "hallucinated_code";
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {
            $type: "security_gap" | "logic_error" | "context_blindness" | "outdated_api" | "missing_edge_case" | "poor_readability" | "broke_existing" | "hallucinated_code";
        }>;
        failureSeverity: import("drizzle-orm/pg-core").PgColumn<{
            name: "failure_severity";
            tableName: "agent_reports";
            dataType: "string";
            columnType: "PgText";
            data: "low" | "medium" | "high" | "critical";
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {
            $type: "low" | "medium" | "high" | "critical";
        }>;
        filePath: import("drizzle-orm/pg-core").PgColumn<{
            name: "file_path";
            tableName: "agent_reports";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        language: import("drizzle-orm/pg-core").PgColumn<{
            name: "language";
            tableName: "agent_reports";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        context: import("drizzle-orm/pg-core").PgColumn<{
            name: "context";
            tableName: "agent_reports";
            dataType: "json";
            columnType: "PgJsonb";
            data: unknown;
            driverParam: unknown;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        createdAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "created_at";
            tableName: "agent_reports";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const insertAgentReportSchema: z.ZodObject<Omit<{
    id: z.ZodOptional<z.ZodString>;
    projectId: z.ZodString;
    externalAgent: z.ZodString;
    sessionId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    action: z.ZodString;
    codeGenerated: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    codeAccepted: z.ZodOptional<z.ZodNullable<z.ZodBoolean>>;
    humanCorrection: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    errorMessage: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    failureCategory: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    failureSeverity: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    filePath: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    language: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    context: z.ZodOptional<z.ZodNullable<z.ZodType<import("drizzle-zod").Json, z.ZodTypeDef, import("drizzle-zod").Json>>>;
    createdAt: z.ZodOptional<z.ZodDate>;
}, "id" | "createdAt">, "strip", z.ZodTypeAny, {
    action: string;
    projectId: string;
    externalAgent: string;
    filePath?: string | null | undefined;
    errorMessage?: string | null | undefined;
    sessionId?: string | null | undefined;
    codeGenerated?: string | null | undefined;
    codeAccepted?: boolean | null | undefined;
    humanCorrection?: string | null | undefined;
    failureCategory?: string | null | undefined;
    failureSeverity?: string | null | undefined;
    language?: string | null | undefined;
    context?: import("drizzle-zod").Json | undefined;
}, {
    action: string;
    projectId: string;
    externalAgent: string;
    filePath?: string | null | undefined;
    errorMessage?: string | null | undefined;
    sessionId?: string | null | undefined;
    codeGenerated?: string | null | undefined;
    codeAccepted?: boolean | null | undefined;
    humanCorrection?: string | null | undefined;
    failureCategory?: string | null | undefined;
    failureSeverity?: string | null | undefined;
    language?: string | null | undefined;
    context?: import("drizzle-zod").Json | undefined;
}>;
export type InsertAgentReport = z.infer<typeof insertAgentReportSchema>;
export type AgentReport = typeof agentReports.$inferSelect;
export declare const projectGuidelines: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "project_guidelines";
    schema: undefined;
    columns: {
        id: import("drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "project_guidelines";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {
            length: number | undefined;
        }>;
        projectId: import("drizzle-orm/pg-core").PgColumn<{
            name: "project_id";
            tableName: "project_guidelines";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        rulesMarkdown: import("drizzle-orm/pg-core").PgColumn<{
            name: "rules_markdown";
            tableName: "project_guidelines";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        ruleCount: import("drizzle-orm/pg-core").PgColumn<{
            name: "rule_count";
            tableName: "project_guidelines";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        confidence: import("drizzle-orm/pg-core").PgColumn<{
            name: "confidence";
            tableName: "project_guidelines";
            dataType: "number";
            columnType: "PgReal";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        observationCount: import("drizzle-orm/pg-core").PgColumn<{
            name: "observation_count";
            tableName: "project_guidelines";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        enabledCategories: import("drizzle-orm/pg-core").PgColumn<{
            name: "enabled_categories";
            tableName: "project_guidelines";
            dataType: "array";
            columnType: "PgArray";
            data: string[];
            driverParam: string | string[];
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: import("drizzle-orm").Column<{
                name: "enabled_categories";
                tableName: "project_guidelines";
                dataType: "string";
                columnType: "PgText";
                data: string;
                driverParam: string;
                notNull: false;
                hasDefault: false;
                isPrimaryKey: false;
                isAutoincrement: false;
                hasRuntimeDefault: false;
                enumValues: [string, ...string[]];
                baseColumn: never;
                identity: undefined;
                generated: undefined;
            }, {}, {}>;
            identity: undefined;
            generated: undefined;
        }, {}, {
            baseBuilder: import("drizzle-orm/pg-core").PgColumnBuilder<{
                name: "enabled_categories";
                dataType: "string";
                columnType: "PgText";
                data: string;
                enumValues: [string, ...string[]];
                driverParam: string;
            }, {}, {}, import("drizzle-orm").ColumnBuilderExtraConfig>;
            size: undefined;
        }>;
        crossProjectLearning: import("drizzle-orm/pg-core").PgColumn<{
            name: "cross_project_learning";
            tableName: "project_guidelines";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: false;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        createdAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "created_at";
            tableName: "project_guidelines";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        updatedAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "updated_at";
            tableName: "project_guidelines";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const insertProjectGuidelinesSchema: z.ZodObject<Omit<{
    id: z.ZodOptional<z.ZodString>;
    projectId: z.ZodString;
    rulesMarkdown: z.ZodString;
    ruleCount: z.ZodNumber;
    confidence: z.ZodNumber;
    observationCount: z.ZodNumber;
    enabledCategories: z.ZodOptional<z.ZodNullable<z.ZodArray<z.ZodString, "many">>>;
    crossProjectLearning: z.ZodOptional<z.ZodNullable<z.ZodBoolean>>;
    createdAt: z.ZodOptional<z.ZodDate>;
    updatedAt: z.ZodOptional<z.ZodDate>;
}, "id" | "createdAt" | "updatedAt">, "strip", z.ZodTypeAny, {
    confidence: number;
    projectId: string;
    rulesMarkdown: string;
    ruleCount: number;
    observationCount: number;
    enabledCategories?: string[] | null | undefined;
    crossProjectLearning?: boolean | null | undefined;
}, {
    confidence: number;
    projectId: string;
    rulesMarkdown: string;
    ruleCount: number;
    observationCount: number;
    enabledCategories?: string[] | null | undefined;
    crossProjectLearning?: boolean | null | undefined;
}>;
export type InsertProjectGuidelines = z.infer<typeof insertProjectGuidelinesSchema>;
export type ProjectGuidelines = typeof projectGuidelines.$inferSelect;
export declare const failurePatterns: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "failure_patterns";
    schema: undefined;
    columns: {
        id: import("drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "failure_patterns";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {
            length: number | undefined;
        }>;
        projectId: import("drizzle-orm/pg-core").PgColumn<{
            name: "project_id";
            tableName: "failure_patterns";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        category: import("drizzle-orm/pg-core").PgColumn<{
            name: "category";
            tableName: "failure_patterns";
            dataType: "string";
            columnType: "PgText";
            data: "security_gap" | "logic_error" | "context_blindness" | "outdated_api" | "missing_edge_case" | "poor_readability" | "broke_existing" | "hallucinated_code";
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {
            $type: "security_gap" | "logic_error" | "context_blindness" | "outdated_api" | "missing_edge_case" | "poor_readability" | "broke_existing" | "hallucinated_code";
        }>;
        pattern: import("drizzle-orm/pg-core").PgColumn<{
            name: "pattern";
            tableName: "failure_patterns";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        occurrences: import("drizzle-orm/pg-core").PgColumn<{
            name: "occurrences";
            tableName: "failure_patterns";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        exampleCodes: import("drizzle-orm/pg-core").PgColumn<{
            name: "example_codes";
            tableName: "failure_patterns";
            dataType: "array";
            columnType: "PgArray";
            data: string[];
            driverParam: string | string[];
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: import("drizzle-orm").Column<{
                name: "example_codes";
                tableName: "failure_patterns";
                dataType: "string";
                columnType: "PgText";
                data: string;
                driverParam: string;
                notNull: false;
                hasDefault: false;
                isPrimaryKey: false;
                isAutoincrement: false;
                hasRuntimeDefault: false;
                enumValues: [string, ...string[]];
                baseColumn: never;
                identity: undefined;
                generated: undefined;
            }, {}, {}>;
            identity: undefined;
            generated: undefined;
        }, {}, {
            baseBuilder: import("drizzle-orm/pg-core").PgColumnBuilder<{
                name: "example_codes";
                dataType: "string";
                columnType: "PgText";
                data: string;
                enumValues: [string, ...string[]];
                driverParam: string;
            }, {}, {}, import("drizzle-orm").ColumnBuilderExtraConfig>;
            size: undefined;
        }>;
        exampleCorrections: import("drizzle-orm/pg-core").PgColumn<{
            name: "example_corrections";
            tableName: "failure_patterns";
            dataType: "array";
            columnType: "PgArray";
            data: string[];
            driverParam: string | string[];
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: import("drizzle-orm").Column<{
                name: "example_corrections";
                tableName: "failure_patterns";
                dataType: "string";
                columnType: "PgText";
                data: string;
                driverParam: string;
                notNull: false;
                hasDefault: false;
                isPrimaryKey: false;
                isAutoincrement: false;
                hasRuntimeDefault: false;
                enumValues: [string, ...string[]];
                baseColumn: never;
                identity: undefined;
                generated: undefined;
            }, {}, {}>;
            identity: undefined;
            generated: undefined;
        }, {}, {
            baseBuilder: import("drizzle-orm/pg-core").PgColumnBuilder<{
                name: "example_corrections";
                dataType: "string";
                columnType: "PgText";
                data: string;
                enumValues: [string, ...string[]];
                driverParam: string;
            }, {}, {}, import("drizzle-orm").ColumnBuilderExtraConfig>;
            size: undefined;
        }>;
        suggestedRule: import("drizzle-orm/pg-core").PgColumn<{
            name: "suggested_rule";
            tableName: "failure_patterns";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        confidence: import("drizzle-orm/pg-core").PgColumn<{
            name: "confidence";
            tableName: "failure_patterns";
            dataType: "number";
            columnType: "PgReal";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        isGlobal: import("drizzle-orm/pg-core").PgColumn<{
            name: "is_global";
            tableName: "failure_patterns";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: false;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        createdAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "created_at";
            tableName: "failure_patterns";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        updatedAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "updated_at";
            tableName: "failure_patterns";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const insertFailurePatternSchema: z.ZodObject<Omit<{
    id: z.ZodOptional<z.ZodString>;
    projectId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    category: z.ZodString;
    pattern: z.ZodString;
    occurrences: z.ZodOptional<z.ZodNumber>;
    exampleCodes: z.ZodOptional<z.ZodNullable<z.ZodArray<z.ZodString, "many">>>;
    exampleCorrections: z.ZodOptional<z.ZodNullable<z.ZodArray<z.ZodString, "many">>>;
    suggestedRule: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    confidence: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    isGlobal: z.ZodOptional<z.ZodNullable<z.ZodBoolean>>;
    createdAt: z.ZodOptional<z.ZodDate>;
    updatedAt: z.ZodOptional<z.ZodDate>;
}, "id" | "createdAt" | "updatedAt">, "strip", z.ZodTypeAny, {
    pattern: string;
    category: string;
    confidence?: number | null | undefined;
    projectId?: string | null | undefined;
    occurrences?: number | undefined;
    exampleCodes?: string[] | null | undefined;
    exampleCorrections?: string[] | null | undefined;
    suggestedRule?: string | null | undefined;
    isGlobal?: boolean | null | undefined;
}, {
    pattern: string;
    category: string;
    confidence?: number | null | undefined;
    projectId?: string | null | undefined;
    occurrences?: number | undefined;
    exampleCodes?: string[] | null | undefined;
    exampleCorrections?: string[] | null | undefined;
    suggestedRule?: string | null | undefined;
    isGlobal?: boolean | null | undefined;
}>;
export type InsertFailurePattern = z.infer<typeof insertFailurePatternSchema>;
export type FailurePattern = typeof failurePatterns.$inferSelect;
export interface MonitorAnalytics {
    totalReports: number;
    failuresByCategory: Record<FailureCategory, number>;
    failuresByAgent: Record<ExternalAgentType, number>;
    failuresBySeverity: Record<FailureSeverity, number>;
    topPatterns: Array<{
        pattern: string;
        occurrences: number;
        category: FailureCategory;
    }>;
    recentTrend: Array<{
        date: string;
        count: number;
    }>;
}
//# sourceMappingURL=schema.d.ts.map