/**
 * Project Initialization for AI Coding Agents
 * 
 * Auto-configures host projects to enable agent reporting.
 * 
 * Usage:
 * ```bash
 * npx ai-agents init --framework express --orm drizzle
 * ```
 */

import * as fs from 'fs';
import * as path from 'path';

export interface InitOptions {
  framework: 'express' | 'fastify' | 'koa' | 'hono';
  orm: 'drizzle' | 'prisma' | 'none';
  projectPath: string;
  projectId?: string;
  hubUrl?: string;
}

export interface InitResult {
  success: boolean;
  filesCreated: string[];
  filesModified: string[];
  instructions: string[];
  errors: string[];
}

/**
 * Initialize a project for AI agent reporting
 */
export async function initProject(options: InitOptions): Promise<InitResult> {
  const result: InitResult = {
    success: false,
    filesCreated: [],
    filesModified: [],
    instructions: [],
    errors: []
  };
  
  const { framework, orm, projectPath, projectId, hubUrl } = options;
  
  try {
    if (!fs.existsSync(projectPath)) {
      result.errors.push(`Project path does not exist: ${projectPath}`);
      return result;
    }

    const configFile = path.join(projectPath, '.ai-agents.json');
    const config = {
      projectId: projectId || path.basename(projectPath),
      hubUrl: hubUrl || 'http://localhost:5000',
      autoSync: true,
      rulesFile: 'AGENT_RULES.md',
      reporting: {
        enabled: true,
        onCommit: true,
        onMerge: true
      }
    };
    
    fs.writeFileSync(configFile, JSON.stringify(config, null, 2));
    result.filesCreated.push('.ai-agents.json');

    const wrapperPath = path.join(projectPath, 'scripts', 'ai-agents.sh');
    const scriptsDir = path.join(projectPath, 'scripts');
    
    if (!fs.existsSync(scriptsDir)) {
      fs.mkdirSync(scriptsDir, { recursive: true });
    }
    
    const wrapperContent = `#!/bin/bash
# AI Coding Agents CLI Wrapper
# Auto-generated by: npx ai-agents init

export AI_AGENTS_API_URL="${hubUrl || 'http://localhost:5000'}/api/agents"
export AI_AGENTS_PROJECT_ID="${config.projectId}"
export AI_AGENTS_LOG_HTTP="${hubUrl || 'http://localhost:5000'}/api/agents/logs/ingest"
export AI_AGENTS_LOG_LEVEL="info"

npx ai-agents "$@"
`;
    
    fs.writeFileSync(wrapperPath, wrapperContent);
    fs.chmodSync(wrapperPath, 0o755);
    result.filesCreated.push('scripts/ai-agents.sh');

    if (orm === 'drizzle') {
      const schemaSnippet = `
// Add to your shared/schema.ts:
import { 
  agentReportsTable, 
  agentLogsTable,
  projectGuidelinesTable 
} from 'ai-coding-agents/drizzle';

export { agentReportsTable, agentLogsTable, projectGuidelinesTable };
`;
      result.instructions.push('Add Drizzle schema to shared/schema.ts:');
      result.instructions.push(schemaSnippet);
    }

    if (framework === 'express') {
      const routerSnippet = `
// Add to your server/routes.ts or main server file:
import { createAgentRouter } from 'ai-coding-agents/express';
import { storage } from './storage'; // Your storage implementation

// Mount the agent router
app.use('/api/agents', createAgentRouter(storage));
`;
      result.instructions.push('Mount the Express router:');
      result.instructions.push(routerSnippet);
    }

    result.instructions.push('\nInstall git hooks for automatic reporting:');
    result.instructions.push('  npx ai-agents hooks install');
    
    result.instructions.push('\nTest the connection:');
    result.instructions.push('  ./scripts/ai-agents.sh analytics');

    result.success = true;
    
  } catch (error) {
    result.errors.push(`Initialization failed: ${error instanceof Error ? error.message : String(error)}`);
  }
  
  return result;
}

/**
 * Generate storage implementation scaffold
 */
export function generateStorageScaffold(orm: 'drizzle' | 'prisma' | 'none'): string {
  if (orm === 'drizzle') {
    return `
import { db } from './db';
import { agentReportsTable, agentLogsTable } from 'ai-coding-agents/drizzle';
import { IAgentStorage, detectFailure, categorizeFailure } from 'ai-coding-agents/express';
import { v4 as uuidv4 } from 'uuid';
import { eq, desc, sql } from 'drizzle-orm';

export const storage: IAgentStorage = {
  async createAgentReport(input) {
    const failure = categorizeFailure(input);
    const report = {
      ...input,
      reportId: uuidv4(),
      detectedFailure: detectFailure(input),
      failureCategory: failure?.category,
      failureSeverity: failure?.severity,
    };
    
    const [inserted] = await db.insert(agentReportsTable).values(report).returning();
    return inserted;
  },
  
  async getAgentReports(projectId, limit = 100) {
    let query = db.select().from(agentReportsTable).orderBy(desc(agentReportsTable.createdAt)).limit(limit);
    if (projectId) {
      query = query.where(eq(agentReportsTable.projectId, projectId));
    }
    return await query;
  },
  
  async getAgentAnalytics(projectId) {
    const reports = await this.getAgentReports(projectId, 1000);
    const total = reports.length;
    const accepted = reports.filter(r => r.codeAccepted === true).length;
    
    const failuresByCategory: Record<string, number> = {};
    const failuresBySeverity: Record<string, number> = {};
    
    for (const r of reports) {
      if (r.failureCategory) {
        failuresByCategory[r.failureCategory] = (failuresByCategory[r.failureCategory] || 0) + 1;
      }
      if (r.failureSeverity) {
        failuresBySeverity[r.failureSeverity] = (failuresBySeverity[r.failureSeverity] || 0) + 1;
      }
    }
    
    return {
      totalReports: total,
      acceptanceRate: total > 0 ? accepted / total : 1,
      failuresByCategory,
      failuresBySeverity,
      topPatterns: []
    };
  },
  
  async ingestAgentLog(log) {
    const [inserted] = await db.insert(agentLogsTable).values({
      ...log,
      timestamp: log.timestamp ? new Date(log.timestamp) : new Date(),
    }).returning();
    return { id: inserted.id };
  },
  
  async getAgentLogs(options) {
    let query = db.select().from(agentLogsTable).orderBy(desc(agentLogsTable.receivedAt)).limit(options.limit || 100);
    if (options.runId) query = query.where(eq(agentLogsTable.runId, options.runId));
    if (options.level) query = query.where(eq(agentLogsTable.level, options.level));
    return await query;
  },
  
  async getAgentLogStats() {
    const logs = await db.select().from(agentLogsTable).limit(1000);
    const byLevel: Record<string, number> = {};
    const byAgent: Record<string, number> = {};
    
    for (const log of logs) {
      byLevel[log.level] = (byLevel[log.level] || 0) + 1;
      if (log.agentType) byAgent[log.agentType] = (byAgent[log.agentType] || 0) + 1;
    }
    
    return {
      totalLogs: logs.length,
      byLevel,
      byAgent,
      errorCount: byLevel['error'] || 0,
      recentRuns: []
    };
  }
};
`;
  }
  
  return `
// Manual storage implementation required
// Implement the IAgentStorage interface from 'ai-coding-agents/express'
`;
}
